definitions:
  Column:
    properties:
      id:
        type: string
      title:
        type: string
      type:
        $ref: '#/definitions/xlsx.Type'
      width:
        type: number
    type: object
  Sheet:
    properties:
      columns:
        items:
          $ref: '#/definitions/Column'
        type: array
      data:
        items:
          additionalProperties: {}
          type: object
        type: array
      name:
        type: string
    type: object
  XlsxRequest:
    properties:
      sheets:
        items:
          $ref: '#/definitions/Sheet'
        type: array
    type: object
  xlsx.Type:
    enum:
    - INT
    - DATE
    - FLOAT
    - STRING
    type: string
    x-enum-varnames:
    - INT
    - DATE
    - FLOAT
    - STRING
info:
  contact: {}
  description: Service to read and writer xlsx.
  termsOfService: http://swagger.io/terms/
  title: Excel Reader and Writer
  version: "1.0"
paths:
  /reader:
    post:
      consumes:
      - multipart/form-data
      description: Reader excel file and return data
      parameters:
      - description: this is a excel file
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: ok
          schema:
            items:
              items:
                type: string
              type: array
            type: array
      tags:
      - Reader
  /writer:
    post:
      consumes:
      - application/json
      description: Create excel file
      parameters:
      - description: Payload
        in: body
        name: Payload
        required: true
        schema:
          $ref: '#/definitions/XlsxRequest'
      produces:
      - application/vnd.ms-excel
      responses:
        "200":
          description: OK
          schema:
            type: file
      tags:
      - Writer
swagger: "2.0"
